steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/thriftify-registry/ml-api:latest', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/thriftify-registry/ml-api:latest']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'ml-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/thriftify-registry/ml-api:latest'
    - '--region'
    - 'asia-southeast2'
  images:
  - 'gcr.io/$PROJECT_ID/thriftify-registry/ml-api:latest'